### ISSUE TITLE
panic: line style LineStyleLight line part linePartHAndUp is a rune ┴ with width 2, all parts must be half-width runes (width of one)

### ISSUE THREAD

**Issue by pathbox** [mum4k/termdash#144] opened 2019-02-20 02:52 UTC
Hi,
    I run the code from `https://github.com/mum4k/termdash/blob/master/widgets/gauge/gaugedemo/gaugedemo.go` in my Mac, but it panic:

```
panic: line style LineStyleLight line part linePartHAndUp is a rune ┴ with width 2, all parts must be half-width runes (width of one)

goroutine 1 [running]:
github.com/mum4k/termdash/draw.init.0()
	/Users/pathbox/gowork/src/github.com/mum4k/termdash/draw/line_style.go:76 +0x294
exit status 2
```
I don't know the reason

It can't run in macOS(10.14.3) ?

I try another demo, the same question is happened,too.

I find the source code is:

```
func init() {
	for ls, parts := range lineStyleChars {
		for part, r := range parts {
			if got := runewidth.RuneWidth(r); got > 1 {
				panic(fmt.Errorf("line style %v line part %v is a rune %c with width %v, all parts must be half-width runes (width of one)", ls, part, r, got))
			}
		}
	}
}
```

It seems that it is  about rune width of the `hAndUp  '┴'`, I don't know how to solve it

**Comment by mum4k** [comment] 2019-02-20 03:49
Hi, thank you for the bug report. I can confirm that this indeed does work on MacOS, since that is my primary OS.

In order to troubleshoot - could you provide a few more information about your environment? Specifically:

1. What terminal application do you use on MacOS?
1. Can you copy&pate the output of the following command from the terminal application?
```
env | egrep "LANG|CTYPE"
```

**Comment by pathbox** [comment] 2019-02-20 06:51
@mum4k  
terminal application is zsh+ITerm

env | egrep "LANG|CTYPE" is:
```
LANG=zh_CN.UTF-8
LC_CTYPE=zh_CN.UTF-8
```

**Comment by mum4k** [comment] 2019-02-20 06:57
Thank you. Termdash only supports the UTF-8 locale. Characters in other locales might map to different width based on context which resulted in the reported error. Although we should probably improve the error...

To confirm - could you try setting these to en_US.UTF-8 and retry?

That is:
```
export LANG=en_US
export LC_CTYPE=en_US.UTF-8
```

And run any of the demos? Please let me know if that helps.

**Comment by pathbox** [comment] 2019-02-21 02:44
@mum4k Yes, you are right.  I do this:

```
export LANG=en_US
export LC_CTYPE=en_US.UTF-8
```
then it works. 

Do you have the solution about this question? Or you can do some warning in the README

Thank you very much

**Comment by mum4k** [comment] 2019-02-21 02:52
Thank you for confirming this. I think I have a solution. Termdash uses certain characters for drawing (like the line character in the panic) which can have "ambiguous" width in some East-Asian locales.(http://www.unicode.org/reports/tr11/).

This means that the number of cells they occupy depends on the context (the surrounding characters). The library we use to determine the width defensively reports a width of two for these characters since it cannot be sure.

From what I read today - considering that we know the full context of these characters I think it is safe to override the ambiguity and assume they will have a width of one cell even in East-Asian. That might be safe, because we place and know all the other characters around them (lines, boxes, pixels).

I will keep this bug open until I push the fix. If you have the time, I would appreciate if you could test it afterwards.

**Comment by pathbox** [comment] 2019-02-22 02:29
I am glad to test it afterwards

**Comment by mum4k** [comment] 2019-02-22 05:20
Thank you again for the bug report. I have pushed the fix into the [devel branch](https://github.com/mum4k/termdash/tree/devel). It isn't released into master yet, but I would appreciate if you could try building from the devel branch.

Can you confirm if it starts without the workaround? You shouldn't need to change the locale anymore.

**Closed by mum4k** 2019-02-22 05:20 UTC
Labels: bug

**Comment by pathbox** [comment] 2019-02-27 03:08
Hi，I try the devel branch ， it panic：
```
gaugedemo.go:13:2: cannot find package "github.com/mum4k/termdash/draw" in any of:
	/usr/local/go/src/github.com/mum4k/termdash/draw (from $GOROOT)
```

the `draw` folder is missing

**Comment by mum4k** [comment] 2019-02-27 03:34
Thank you for finding the time and testing this. Is it possible that you made some local edits to the gaugedemo? I am asking because looking at the gaugedemo, it actually doesn't import "draw" anymore.

https://github.com/mum4k/termdash/blob/275d95ad418b6ecca8817de4b013b440fc9abbe6/widgets/gauge/gaugedemo/gaugedemo.go#L23-L29

Can you also make sure you are synced to the latest commit on the devel branch? I have recently moved the draw package into the internal subdirectory.

It would help me if you could try running an unmodified version of the gaugedemo.

**Comment by pathbox** [comment] 2019-02-27 07:09
Yeah,  and I test the code, it works fine,  you fix it, it is good~

**Comment by mum4k** [comment] 2019-02-27 19:05
Thank you very much for confirming.
